server:
  port: 1234

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: maerdlina
    password: 1234
    url: jdbc:postgresql://localhost:5111/postgres
